/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Zone = IDL.Variant({
  'soundscape' : IDL.Null,
  'artistic' : IDL.Null,
  'devden' : IDL.Null,
});
export const Time = IDL.Int;
export const Post = IDL.Record({
  'title' : IDL.Text,
  'content' : IDL.Text,
  'zone' : Zone,
  'author' : IDL.Text,
  'timestamp' : Time,
});

export const idlService = IDL.Service({
  'addPost' : IDL.Func([IDL.Text, IDL.Text, Zone, IDL.Text], [], []),
  'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Zone = IDL.Variant({
    'soundscape' : IDL.Null,
    'artistic' : IDL.Null,
    'devden' : IDL.Null,
  });
  const Time = IDL.Int;
  const Post = IDL.Record({
    'title' : IDL.Text,
    'content' : IDL.Text,
    'zone' : Zone,
    'author' : IDL.Text,
    'timestamp' : Time,
  });
  
  return IDL.Service({
    'addPost' : IDL.Func([IDL.Text, IDL.Text, Zone, IDL.Text], [], []),
    'getAllPosts' : IDL.Func([], [IDL.Vec(Post)], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };